version: '3.4'
services:
  postgres:
    container_name: "djangolang_pg"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: "djangolang"
      POSTGRES_DB: "djangolang_db"
      POSTGRES_PASSWORD: "djangolang123"
    volumes:
      - ./djangolang_pg_data:/var/lib/postgresql/data

  react:
    container_name: "djangolang_react"
    build:
      context: .
      target: node_builder
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
    ports:
      - "3000:3000" 

  go:
    container_name: "djangolang_go"
    build:
      context: .
      target: go_builder
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
 
